# Version may either be a specific k3s version or a release channel
# as listed here: https://update.k3s.io/v1-release/channels
version: stable

# Cluster provides cluster-wide settings that should be applied
# to all nodes in the cluster. All options are equivalent to the
# commmand line options of the `k3s` command.
cluster:
  server:
    # It is highly recommended to always specify this option as it
    # is used to determine the server URL of the cluster.
    tls-san:
      - 135.181.36.241
    write-kubeconfig-mode: "644"

# A list of all nodes in the cluster and their connection information.
nodes:
  - role: server
    ssh:
      host: 135.181.36.241
      user: root
      key-file: /tmp/k3se-ssh-key
  - role: server
    ssh:
      host: 135.181.145.173
      user: root
      key-file: /tmp/k3se-ssh-key
  - role: server
    ssh:
      host: 65.108.54.2
      user: root
      key-file: /tmp/k3se-ssh-key
