name: Pulumi Preview 

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - stage

jobs:
  up:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup SSH Keys
        shell: bash
        env:
          SSH_DEPLOY_KEY: ${{secrets.SSH_DEPLOY_KEY}}
        run: |
          echo "$SSH_DEPLOY_KEY" > /tmp/k3se-ssh-key

      - name: Setup Node LTS ✨
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm

      - name: Installing dependencies 📦️
        run: npm ci

      - name: Setup k3se
        uses: nicklasfrahm/k3se@main
        with:
          command: --version

      - name: Preview infrastructure 🚀
        uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: adb-sh/turingev/stage
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
